controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    policy_inference:
      type: policy_inference_ros2_control/Ros2ControlPolicyInference

policy_inference:
  ros__parameters:
    backend_plugin: my_fancy_cpp_inference/FancyCppBackend
    model_uri: fancy_cpp.onnx
    output_size: 4
    output_scale: 1.0
    output_bias: 0.0
    demo_input: [1.0, 2.0, 3.0]
